spring:
    security:
        oauth2:
            client:
                registration:
                    naver:
                        # Naver OAuth 설정 값
                        client-id: kMAZuSl0_lDrwveJKo2z
                        client-secret: RwsiSADGPJ
                        # Naver Spring Security 수동 입력. Naver 인증 콜백
                        redirect-uri: http://localhost:8080/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        scope: name,email
                        client-name: Naver
                    google:
                        # Google OAuth 설정 값
                        client-id: 815540232988-gj295cja736dr8gt3g34ebp0vjek5gfr.apps.googleusercontent.com
                        client-secret: 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
                        scope: profile,email
                    github:
                        # Github OAuth 설정 값
                        client-id: Ov23liQsM3rgu9xlM4K6
                        client-secret: 3e38c58f374b11e0f9f64ff2dc1deef624572e57
                        scope: name,email
                provider:
                    naver:
                        # provider 로그인한 사용자의 계정 정보 얻어오기
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        # Security의 기준이 되는 username의 이름을 네이버에서는 response로 (회원 조회 시 반환되는 JSON 형태 때문)
                        user-name-attribute: response
    application.name: hello-spring
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:XE
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: SPRING_BOOT
        password: 1234
#    mvc:
#        view:
#            prefix: /WEB-INF/views/
#            suffix: .jsp
    servlet:
        # 파일 업로드 설정
        multipart:
            # 1024byte -> 1kb -> 1024kb -> 1mb
            #최대 업로드 파일 크기 설정(100MB : 1024 * 1024 * 100)
            max-file-size: 104857600
            # 요청당 최대 업로드 파일 크기 설정 (10MB : 1024 * 1024 * 10)
            max-request-size: 10485760
            
# classpath: ==> Java, XML 이런 파일을 가지고 있는 프로젝트 정보들이 컴파일되어
#                보관하는 경로.
# C:\dev_programs\sts_workspace\hello-spring\target\classes : classpath
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:com/hello/forum/**/dao/mapper/*Mapper.xml

# 사용자 설정
app:
    jwt:
        issuer: mcjang1116@gmail.com
        secret-key: spring-security-key-random-token-key
    authentication:
        check-url-pattern: /**
        ignore-url-patterns:
            /member/regist/**,
            /member/login,
            /ajax/member/regist/**,
            /ajax/member/login,
            /member/logout,
            /member/success-delete-me,
            /member/fail-delete-me,
            /board/search,
            /js/**,
            /css/**,
            /error/**,
            /ajax/menu/list
    multipart:
        # 파일 업로드 위치 지정
        base-dir: c:/uploadFiles
        # 난독화 여부 설정
        obfuscation:
            # 파일명 난독화 할 경우 true
            enable: true
            # 파일 확장자 가리기 여부 설정
            hide-ext:
                # 파일 확장자 가릴 경우 true
                enable: true
        available-file-list:
            handler: tika
            enable: true
            list:
                audio/aac,
                video/x-msvideo,
                text/css,
                text/csv,
                application/msword,
                image/gif,
                text/html,
                image/jpeg,
                application/json,
                audio/midi,
                video/mpeg,
                audio/ogg,
                video/ogg,
                application/ogg,
                application/pdf,
                application/vnd.ms-powerpoint,
                image/png,
                image/tiff,
                application/vnd.ms-excel,
                application/zip,
                application/vnd.openxmlformats-officedocument.wordprocessingml.document,
                application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,
                application/vnd.openxmlformats-officedocument.wordprocessingml.document,
                application/vnd.openxmlformats-officedocument.presentationml.presentation,
                text/plain,
                application/x-tika-ooxml,
                application/vnd.openxmlformats-officedocument.wordprocessingml.document
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                